#!/bin/bash

rm -f /var/tmp/denoPerfResults/*
deno_cmd="deno run --unstable --allow-read --allow-net --allow-write tester.ts";
repeat="1000"
runType1="-o f -c 1 -r $repeat"
runType2="-o f -c 10 -r $repeat"
runType3="-o f -c 50 -r $repeat"
runType4="-o f -c 100 -r $repeat"

if [ "$1" = "1" ]; then

    $deno_cmd -u http://localhost:8000 -n deno__hello_world $runType1
    $deno_cmd -u http://localhost:3000 -n node__hello_world $runType1
    $deno_cmd -u http://localhost:8000 -n deno__hello_world $runType2
    $deno_cmd -u http://localhost:3000 -n node__hello_world $runType2
    $deno_cmd -u http://localhost:8000 -n deno__hello_world $runType3
    $deno_cmd -u http://localhost:3000 -n node__hello_world $runType3
    $deno_cmd -u http://localhost:8000 -n deno__hello_world $runType4
    $deno_cmd -u http://localhost:3000 -n node__hello_world $runType4


elif [ "$1" = "2" ]; then

    $deno_cmd -u http://localhost:8000 -n deno__redis_regex_uuid $runType1 -d '{"key": "jkey"}'
    $deno_cmd -u http://localhost:3000 -n node__redis_regex_uuid $runType1 -d '{"key": "jkey"}'
    $deno_cmd -u http://localhost:8000 -n deno__redis_regex_uuid $runType2 -d '{"key": "jkey"}'
    $deno_cmd -u http://localhost:3000 -n node__redis_regex_uuid $runType2 -d '{"key": "jkey"}'
    $deno_cmd -u http://localhost:8000 -n deno__redis_regex_uuid $runType3 -d '{"key": "jkey"}'
    $deno_cmd -u http://localhost:3000 -n node__redis_regex_uuid $runType3 -d '{"key": "jkey"}'
    $deno_cmd -u http://localhost:8000 -n deno__redis_regex_uuid $runType4 -d '{"key": "jkey"}'
    $deno_cmd -u http://localhost:3000 -n node__redis_regex_uuid $runType4 -d '{"key": "jkey"}'


    
fi

cat /var/tmp/denoPerfResults/*