#!/bin/bash

rm -f /var/tmp/denoPerfResults/*
deno_cmd="deno run --unstable --allow-read --allow-net --allow-write tester.ts";
deno_cmd_cert="deno run --cert ../deno-vs-nodejs/certs/RootCA.pem --unstable --allow-read --allow-net --allow-write tester.ts";
repeat="1000"
runType1="-o f -c 1 -r $repeat"
runType10="-o f -c 10 -r $repeat"
runType50="-o f -c 50 -r $repeat"
runType100="-o f -c 100 -r $repeat"

if [ "$1" = "1" ]; then

    $deno_cmd -u http://localhost:8000 -n deno__hello_world $runType1
    $deno_cmd -u http://localhost:3000 -n node__hello_world $runType1
    $deno_cmd -u http://localhost:8000 -n deno__hello_world $runType10
    $deno_cmd -u http://localhost:3000 -n node__hello_world $runType10
    $deno_cmd -u http://localhost:8000 -n deno__hello_world $runType50
    $deno_cmd -u http://localhost:3000 -n node__hello_world $runType50
    $deno_cmd -u http://localhost:8000 -n deno__hello_world $runType100
    $deno_cmd -u http://localhost:3000 -n node__hello_world $runType100


elif [ "$1" = "2" ]; then

    $deno_cmd -u http://localhost:8000 -n deno__redis_regex_uuid $runType1 -d '{"key": "jkey"}'
    $deno_cmd -u http://localhost:3000 -n node__redis_regex_uuid $runType1 -d '{"key": "jkey"}'
    $deno_cmd -u http://localhost:8000 -n deno__redis_regex_uuid $runType10 -d '{"key": "jkey"}'
    $deno_cmd -u http://localhost:3000 -n node__redis_regex_uuid $runType10 -d '{"key": "jkey"}'
    $deno_cmd -u http://localhost:8000 -n deno__redis_regex_uuid $runType50 -d '{"key": "jkey"}'
    $deno_cmd -u http://localhost:3000 -n node__redis_regex_uuid $runType50 -d '{"key": "jkey"}'
    $deno_cmd -u http://localhost:8000 -n deno__redis_regex_uuid $runType100 -d '{"key": "jkey"}'
    $deno_cmd -u http://localhost:3000 -n node__redis_regex_uuid $runType100 -d '{"key": "jkey"}'


elif [ "$1" = "3" ]; then

    $deno_cmd_cert -u https://localhost:8000 -n deno__https_hello_name $runType1 -d '{"name": "MyName1"}'
    $deno_cmd_cert -u https://localhost:3000 -n node__https_hello_name $runType1 -d '{"name": "MyName1"}'
    $deno_cmd_cert -u https://localhost:8000 -n deno__https_hello_name $runType10 -d '{"name": "MyName1"}'
    $deno_cmd_cert -u https://localhost:3000 -n node__https_hello_name $runType10 -d '{"name": "MyName1"}'
    $deno_cmd_cert -u https://localhost:8000 -n deno__https_hello_name $runType50 -d '{"name": "MyName1"}'
    $deno_cmd_cert -u https://localhost:3000 -n node__https_hello_name $runType50 -d '{"name": "MyName1"}'
    $deno_cmd_cert -u https://localhost:8000 -n deno__https_hello_name $runType100 -d '{"name": "MyName1"}'
    $deno_cmd_cert -u https://localhost:3000 -n node__https_hello_name $runType100 -d '{"name": "MyName1"}'


elif [ "$1" = "9" ]; then

    repeat="1000"
    for i in {1..5}; do $deno_cmd -u http://localhost:3000 -n node__hello_world$i -o f -c 50 -r $repeat; done
    #$deno_cmd -u http://localhost:3000 -n node__hello_world -o f -c 10 -r $repeat
    

fi

cat /var/tmp/denoPerfResults/*
